### ISSUE TITLE
Keep Object.constructor.name

### ISSUE THREAD

**Issue by ceremcem** [aktos-io/scada.js#172]
Any code may rely on `obj.constructor.name` which is replaced by the letter `t` in `--production` build: 

https://github.com/mishoo/UglifyJS2/issues/1429

**Comment by yairEO** [comment]
So what's the fix? which rules should I give to specifically not replace `*.constructor` with `t` ?

**Comment by ceremcem** [comment]
Are you using ScadaJS or you have a separate project? If you use ScadaJS, you don't need to do anything, it should be already fixed. If you have a separate project, it's better to provide some more information, such as your build script and/or the test case.
