### ISSUE TITLE
date-picker should accept null or 0 time stamps

### ISSUE THREAD

**Issue by ozanmuyes** [aktos-io/scada.js#25]
In order to sustain two way data binding mechanism, even when the initial `unix` value didn't provided as a valid Unix time stamp, the component should be able to handle this particular necessity. Also if date-time didn't changed upon tear down, the key value (`unix') should be pristine.

**Comment by ceremcem** [comment]
Should be fixed as of [v0.3](https://github.com/aktos-io/scada.js/tree/v0.3): http://scadajs.surge.sh/showcase/#date-picker

**Comment by ceremcem** [comment]
Closing due to timeout.
