### ISSUE TITLE
search-combobox should be case insensitive, correlated with locale!

### ISSUE THREAD

**Issue by ceremcem** [aktos-io/scada.js#5]
TEST CASE: Words `ÇALIŞ ÖĞÜN` can be searched with `çalış öğün`.

**Comment by ceremcem** [comment]
https://github.com/selectize/selectize.js/issues/1217

**Comment by dacsy** [comment]
It might a old topic, but could you give me an advise about the question:
How can I search by accent ? I am having problem with search by accent we use UTF-8.

**Comment by ceremcem** [comment]
Nope, it's still open. In fact we are switching to https://github.com/aktos-io/scada.js/tree/switch-to-semantic-ui branch. If you like you can checkout that branch where this problem correlates with semantic-ui's dropdown: https://semantic-ui.com/modules/dropdown.html

**Comment by ceremcem** [comment]
Solved in the dev branch. [*](https://github.com/selectize/selectize.js/issues/719#issuecomment-362914876)
