### ISSUE TITLE
Edit mode of formal-field looks ugly

### ISSUE THREAD

**Issue by sultanDMTR** [aktos-io/scada.js#53]
![image](https://cloud.githubusercontent.com/assets/19163582/22516904/05a04426-e8b0-11e6-9446-ff50869f2ed7.png)

**Comment by ceremcem** [comment]
`formal-field`'s edit mode looks very well now (by https://github.com/aktos-io/scada.js/pull/75): 

![image](https://cloud.githubusercontent.com/assets/6639874/22941828/b79a7a0e-f2ef-11e6-8726-8c773c8b4bdf.png)
