### ISSUE TITLE
r-table breaks input-field and formal-field

### ISSUE THREAD

**Issue by sultanDMTR** [aktos-io/scada.js#63]
This is the expected view of `input-field` component from the showcase:
![image](https://cloud.githubusercontent.com/assets/19163582/22749651/be574434-ee36-11e6-8580-bc53f416c38d.png)

However if `input-field` is placed in `data-table`'s edit-form, it looks as follows: 
![image](https://cloud.githubusercontent.com/assets/19163582/22749697/eb7a6ac2-ee36-11e6-8afa-f9ffa410eebf.png)
 
## Reproduce 
Issue can be reproduced by the following PR: https://github.com/aktos-io/scada.js/pull/62

1. Navigate to `data-table` section in http://localhost:4001/showcase.html
2. Click a row to open view-form
3. Click pencil checkbox to open edit-form an d see the screenshot above

**Comment by sultanDMTR** [comment]
![screenshot - 02082017 - 08 25 21 pm](https://cloud.githubusercontent.com/assets/19163582/22748939/672071b0-ee34-11e6-9dd1-b03d3a35e566.png) this is the current view of input-field component and in data-table component when it used we expect the same view but current view: 
![screenshot - 02082017 - 08 24 51 pm](https://cloud.githubusercontent.com/assets/19163582/22749055/b87cd12a-ee34-11e6-8758-caf73647b415.png)

**Comment by ceremcem** [comment]
As of https://github.com/aktos-io/scada.js/pull/68 , this problem is related with `r-table`'s css.

**Comment by sultanDMTR** [comment]
Previous view of `data-table` component is like:

![image](https://cloud.githubusercontent.com/assets/19163582/22787405/e72ce48c-eee4-11e6-940f-47d0007b6125.png)

Right now it looks like:

![image](https://cloud.githubusercontent.com/assets/19163582/22787361/b1bfbb8a-eee4-11e6-9366-b55f6acde7eb.png)

**Comment by ozanmuyes** [comment]
@ceremcem I insist you to merge the PR #64 while we find an proper solution than a work-around.
