### ISSUE TITLE
Misbehaviour on edit-form with input-field

### ISSUE THREAD

**Issue by ozanmuyes** [aktos-io/scada.js#65]
When adding new entries into an item in the data-table component, remove (X) button causes the misbehaviour. To reproduce please follow these steps;

- ~Pull the codes from the PR #64~
- Navigate to [showcase](http://localhost:4001/showcase.html)
- Scroll down to `data-table` panel
- Click 1st item in the list
- Upon load click the edit button on the upper left corner of the `edit-form`
- Click `Add new entry` button
- Fill three inputs
- Click `Add new entry` button again
- But do not enter anything this time _or select unit_
- Click the close (X) button for the second entry
- See the first entry (filled with data) mutates strangely

**Comment by ceremcem** [comment]
No need to merge https://github.com/aktos-io/scada.js/pull/64, I can confirm that we have a bug here.
