### ISSUE TITLE
r-table in data-table's editform causes overflow

### ISSUE THREAD

**Issue by sultanDMTR** [aktos-io/scada.js#76]
## Description: 
`r-table` in `data-table`s editFom is looks overflow
## Screenshot: 
![image](https://cloud.githubusercontent.com/assets/19163582/22975033/c07370c4-f38d-11e6-8e81-761781dbdf53.png)

## Reproduction:

Follow these steps:

1. Merge with PR: #77 
2. Go to: http://localhost:4001/showcase.html
3. Scroll down to `data-table` panel
4. Click `add my new document` button 
5. See -> Table row is overflowing

**Comment by ceremcem** [comment]
As of https://github.com/aktos-io/scada.js/tree/v0.3 there is no such overflowing problem can be reproduced: 

![image](https://cloud.githubusercontent.com/assets/6639874/26766696/5e99a1bc-499f-11e7-94d5-e336dc3541cc.png)

**Comment by ceremcem** [comment]
Closed due to timeout.
